application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvR0Q5dVVsdExVS2swNGRJUE1xVUFpdHphV01aQUZLeTBrWWFlVUZrTmNzIn0.eyJleHAiOjE3NjIzNTQ4MDcsImlhdCI6MTc2MjM1NDUwNywianRpIjoib25ydHJvOmRmNGU2N2NlLWQ5NDQtOTFjOS1iMDI5LTc5YWI5ZDY1ZGFmZCIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWstYXV0aG4uYXBwcy5jaTQxOS5hcGljdXJpby10ZXN0aW5nLm9yZy9yZWFsbXMvcmVnaXN0cnkiLCJzdWIiOiI0NjU3YzQ3OC04NzJlLTRhNTMtOGMwZC1iZWZlODZkNTc4ZmIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJyYXBpZGFzdC1jbGllbnQiLCJzaWQiOiI0NjgxYmQ3MS0yZWRkLTY1NDktNWUyYy0zMGIzNDUyZmI0ZjQiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInNyLWFkbWluIl19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InJlZ2lzdHJ5LWFkbWluIn0.UufHtK4Ow9yryvl73QLOw2W576bu3AGWoESiwQcIDexVYURj1oQxnz8pDqYFBhiBuGOnRictmyhRP_RPhIhEYsj_mx13CnccuKOwVWxtiJyFBFz7sIY5N6iHrVl3AVegUXIlu8Sekx5wG_5t0mAs7apcKBqyZeEaQqSrkvFbvx4CWPlF7ZPEh6am0dgG8OBbPwsHzOQOh4zxS8EoZKTJaEagfdO04dMOdoVQ47WTS7E-lD_e9JD4qPzpGTQ7PLbCOWFq94IKy0qJYUraKW961mVZNhYo1USJgE9IMXLhdmFMDVVHzWOVb9s2pkX0ayu_Pa-feB2S7bfL6ck3jbehQg
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-authn.apps.ci419.apicurio-testing.org/apis/registry/v2
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-authn.apps.ci419.apicurio-testing.org/api-specifications/registry/v2/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
