application:
  authentication:
    headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJKNVg3ZU1kY1F2Z2xRakRvYjJnWXJLMTl6ZE53UVY0VjFDNVdOZDdTLWZrIn0.eyJleHAiOjE3NjgyNjg4OTMsImlhdCI6MTc2ODI2ODU5MywianRpIjoib25ydHJvOjMxYTdmODAzLTUwMjgtZWNkNC01YmYwLTQzN2RkM2YxZmRiZSIsImlzcyI6Imh0dHBzOi8va2V5Y2xvYWsta2V5Y2xvYWsyNi5hcHBzLmNpNDE5LmFwaWN1cmlvLXRlc3Rpbmcub3JnL3JlYWxtcy9yZWdpc3RyeSIsInN1YiI6IjI0ZGUzZjZhLTM5N2YtNGFiYi04NTJlLWUzNWY4ZGRiNWQyMiIsInR5cCI6IkJlYXJlciIsImF6cCI6InJhcGlkYXN0LWNsaWVudCIsInNpZCI6IjUzYThkODZjLWIxZjgtNDMzNi04NjMzLTVjMTViOTM3ZDEyMSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsic3ItYWRtaW4iXX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoicmVnaXN0cnktYWRtaW4ifQ.Hdex-uHesoMElAFmdHHGPkWwgjGOpVszpSpfwGx8NtbjwMeQxcUf5kl8B_ISKT0YlO_4qnxm-8lT2o0EW75gT590kXHPMR6PRD0oF1rM0hfQQmS-aUoBFpbrk8F92hrwzfI7yFgv4DjgRU-9ZUXWxfBLvi8FNTi4naZArV9RgwC1atARcfMDo1JVsszzWu7pY9ulIuBfQC-fa5HSA6nZ9klWHRceSNpxFTpDF-jcWp2jU4Cvkm7k9E-A6pT72u_pq06Z7vdtnW_QVUYkH57LiPKNkA5I4mkrXyjlKCd_dVvWDF124PW5rewIhtlutSQbyDADeLxppqbvTmfb5RYocA
    type: headers
  shortName: ApicurioRegistry
  url: https://registry-app-keycloak26.apps.ci419.apicurio-testing.org/apis/registry/v3
config:
  configVersion: 5
scanners:
  zap:
    activeScan:
      policy: Kubernetes-API-scan
    apiScan:
      apis:
        apiUrl: https://registry-app-keycloak26.apps.ci419.apicurio-testing.org/api-specifications/registry/v3/openapi.json
    report:
      format:
      - json
      - html
    spider:
      maxDuration: 0
    spiderAjax:
      browserId: firefox-headless
      maxDuration: 0
